name: Check Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: Setup GoLang
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO: sgpublic/lombok-plugin-action
        run: |
          go build
          mv ./lombok-plugin-action ./build/action
          cd ./build
          sudo chmod +x action
          action -token $TOKEN -repo $REPO
